/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Align {
    'Center' = 'Center',
    'End' = 'End',
    'Left' = 'Left',
    'Middle' = 'Middle',
    'Right' = 'Right',
    'Start' = 'Start'
}
