/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Alpha {
    'Activate' = 'Activate',
    'Associate' = 'Associate',
    'Background' = 'Background',
    'Copy' = 'Copy',
    'Deactivate' = 'Deactivate',
    'Discrete' = 'Discrete',
    'Disassociate' = 'Disassociate',
    'Extract' = 'Extract',
    'Off' = 'Off',
    'On' = 'On',
    'Opaque' = 'Opaque',
    'Remove' = 'Remove',
    'Set' = 'Set',
    'Shape' = 'Shape',
    'Transparent' = 'Transparent'
}
