/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Cache {
    'Disk' = 'Disk',
    'Distributed' = 'Distributed',
    'Map' = 'Map',
    'Memory' = 'Memory',
    'Ping' = 'Ping'
}
