/* autogenerated file using scripts/generateImEnums.ts */ 
export enum ClipPath {
    'ObjectBoundingBox' = 'ObjectBoundingBox',
    'UserSpace' = 'UserSpace',
    'UserSpaceOnUse' = 'UserSpaceOnUse'
}
