/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Complex {
    'Add' = 'Add',
    'Conjugate' = 'Conjugate',
    'Divide' = 'Divide',
    'MagnitudePhase' = 'MagnitudePhase',
    'Multiply' = 'Multiply',
    'RealImaginary' = 'RealImaginary',
    'Subtract' = 'Subtract'
}
