/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Decoration {
    'LineThrough' = 'LineThrough',
    'None' = 'None',
    'Overline' = 'Overline',
    'Underline' = 'Underline'
}
