/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Dispose {
    'Undefined' = 'Undefined',
    'Background' = 'Background',
    'None' = 'None',
    'Previous' = 'Previous',
    '0_' = '0',
    '1_' = '1',
    '2_' = '2',
    '3_' = '3'
}
