/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Gravity {
    'None' = 'None',
    'Center' = 'Center',
    'East' = 'East',
    'Forget' = 'Forget',
    'NorthEast' = 'NorthEast',
    'North' = 'North',
    'NorthWest' = 'NorthWest',
    'SouthEast' = 'SouthEast',
    'South' = 'South',
    'SouthWest' = 'SouthWest',
    'West' = 'West'
}
