/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Interlace {
    'Line' = 'Line',
    'None' = 'None',
    'Plane' = 'Plane',
    'Partition' = 'Partition',
    'GIF' = 'GIF',
    'JPEG' = 'JPEG',
    'PNG' = 'PNG'
}
