/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Intent {
    'Absolute' = 'Absolute',
    'Perceptual' = 'Perceptual',
    'Relative' = 'Relative',
    'Saturation' = 'Saturation'
}
