/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Layers {
    'Coalesce' = 'Coalesce',
    'CompareAny' = 'CompareAny',
    'CompareClear' = 'CompareClear',
    'CompareOverlay' = 'CompareOverlay',
    'Dispose' = 'Dispose',
    'Optimize' = 'Optimize',
    'OptimizeFrame' = 'OptimizeFrame',
    'OptimizePlus' = 'OptimizePlus',
    'OptimizeTransparency' = 'OptimizeTransparency',
    'RemoveDups' = 'RemoveDups',
    'RemoveZero' = 'RemoveZero',
    'Composite' = 'Composite',
    'Merge' = 'Merge',
    'Flatten' = 'Flatten',
    'Mosaic' = 'Mosaic',
    'TrimBounds' = 'TrimBounds'
}
