/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Method {
    'FillToBorder' = 'FillToBorder',
    'Floodfill' = 'Floodfill',
    'Point' = 'Point',
    'Replace' = 'Replace',
    'Reset' = 'Reset'
}
