/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Noise {
    'Gaussian' = 'Gaussian',
    'Impulse' = 'Impulse',
    'Laplacian' = 'Laplacian',
    'Multiplicative' = 'Multiplicative',
    'Poisson' = 'Poisson',
    'Random' = 'Random',
    'Uniform' = 'Uniform'
}
