/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Orientation {
    'TopLeft' = 'TopLeft',
    'TopRight' = 'TopRight',
    'BottomRight' = 'BottomRight',
    'BottomLeft' = 'BottomLeft',
    'LeftTop' = 'LeftTop',
    'RightTop' = 'RightTop',
    'RightBottom' = 'RightBottom',
    'LeftBottom' = 'LeftBottom'
}
