/* autogenerated file using scripts/generateImEnums.ts */ 
export enum PolicyDomain {
    'Cache' = 'Cache',
    'Coder' = 'Coder',
    'Delegate' = 'Delegate',
    'Filter' = 'Filter',
    'Module' = 'Module',
    'Path' = 'Path',
    'Resource' = 'Resource',
    'System' = 'System'
}
