/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Policy {
    'Path: [built-in]' = 'Path: [built-in]',
    '  Policy: Undefined' = '  Policy: Undefined',
    '    rights: None ' = '    rights: None '
}
