/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Primitive {
    'Alpha' = 'Alpha',
    'Arc' = 'Arc',
    'Bezier' = 'Bezier',
    'Circle' = 'Circle',
    'Color' = 'Color',
    'Ellipse' = 'Ellipse',
    'Image' = 'Image',
    'Line' = 'Line',
    'Matte' = 'Matte',
    'Path' = 'Path',
    'Point' = 'Point',
    'Polygon' = 'Polygon',
    'Polyline' = 'Polyline',
    'Rectangle' = 'Rectangle',
    'RoundRectangle' = 'RoundRectangle',
    'Text' = 'Text'
}
