/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Resource {
    'Resource limits:' = 'Resource limits:',
    '  Width: 107.374MP' = '  Width: 107.374MP',
    '  Height: 107.374MP' = '  Height: 107.374MP',
    '  List length: -1' = '  List length: -1',
    '  Area: 16.0277GP' = '  Area: 16.0277GP',
    '  Memory: 7.4635GiB' = '  Memory: 7.4635GiB',
    '  Map: 14.927GiB' = '  Map: 14.927GiB',
    '  Disk: unlimited' = '  Disk: unlimited',
    '  File: 786432' = '  File: 786432',
    '  Thread: 4' = '  Thread: 4',
    '  Throttle: 0' = '  Throttle: 0',
    '  Time: unlimited' = '  Time: unlimited'
}
