/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Resource {
    'Resource limits:' = 'Resource limits:',
    '  Width: 107.374MP' = '  Width: 107.374MP',
    '  Height: 107.374MP' = '  Height: 107.374MP',
    '  List length: -1' = '  List length: -1',
    '  Area: 16.0275GP' = '  Area: 16.0275GP',
    '  Memory: 7.46337GiB' = '  Memory: 7.46337GiB',
    '  Map: 14.9267GiB' = '  Map: 14.9267GiB',
    '  Disk: unlimited' = '  Disk: unlimited',
    '  File: 3072' = '  File: 3072',
    '  Thread: 4' = '  Thread: 4',
    '  Throttle: 0' = '  Throttle: 0',
    '  Time: unlimited' = '  Time: unlimited'
}
