/* autogenerated file using scripts/generateImEnums.ts */ 
export enum SparseColor {
    'Barycentric' = 'Barycentric',
    'Bilinear' = 'Bilinear',
    'Inverse' = 'Inverse',
    'Shepards' = 'Shepards',
    'Voronoi' = 'Voronoi',
    'Manhattan' = 'Manhattan'
}
