/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Statistic {
    'Gradient' = 'Gradient',
    'Maximum' = 'Maximum',
    'Mean' = 'Mean',
    'Median' = 'Median',
    'Minimum' = 'Minimum',
    'Mode' = 'Mode',
    'NonPeak' = 'NonPeak',
    'RootMeanSquare' = 'RootMeanSquare',
    'RMS' = 'RMS',
    'StandardDeviation' = 'StandardDeviation'
}
