/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Storage {
    'Char' = 'Char',
    'Double' = 'Double',
    'Float' = 'Float',
    'Long' = 'Long',
    'LongLong' = 'LongLong',
    'Quantum' = 'Quantum',
    'Short' = 'Short'
}
