/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Stretch {
    'Any' = 'Any',
    'Condensed' = 'Condensed',
    'Expanded' = 'Expanded',
    'ExtraCondensed' = 'ExtraCondensed',
    'ExtraExpanded' = 'ExtraExpanded',
    'Normal' = 'Normal',
    'SemiCondensed' = 'SemiCondensed',
    'SemiExpanded' = 'SemiExpanded',
    'UltraCondensed' = 'UltraCondensed',
    'UltraExpanded' = 'UltraExpanded'
}
