/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Tool {
    'animate' = 'animate',
    'compare' = 'compare',
    'composite' = 'composite',
    'conjure' = 'conjure',
    'convert' = 'convert',
    'display' = 'display',
    'identify' = 'identify',
    'import' = 'import',
    'mogrify' = 'mogrify',
    'montage' = 'montage',
    'stream' = 'stream'
}
