/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Units {
    'PixelsPerInch' = 'PixelsPerInch',
    'PixelsPerCentimeter' = 'PixelsPerCentimeter',
    '1_' = '1',
    '2_' = '2',
    '3_' = '3'
}
