/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Validate {
    'All' = 'All',
    'Colorspace' = 'Colorspace',
    'Compare' = 'Compare',
    'Composite' = 'Composite',
    'Convert' = 'Convert',
    'FormatsDisk' = 'FormatsDisk',
    'FormatsMap' = 'FormatsMap',
    'FormatsMemory' = 'FormatsMemory',
    'Identify' = 'Identify',
    'ImportExport' = 'ImportExport',
    'Montage' = 'Montage',
    'Stream' = 'Stream',
    'None' = 'None'
}
