/* autogenerated file using scripts/generateImEnums.ts */ 
export enum VirtualPixel {
    'Background' = 'Background',
    'Black' = 'Black',
    'CheckerTile' = 'CheckerTile',
    'Dither' = 'Dither',
    'Edge' = 'Edge',
    'Gray' = 'Gray',
    'HorizontalTile' = 'HorizontalTile',
    'HorizontalTileEdge' = 'HorizontalTileEdge',
    'Mirror' = 'Mirror',
    'None' = 'None',
    'Random' = 'Random',
    'Tile' = 'Tile',
    'Transparent' = 'Transparent',
    'VerticalTile' = 'VerticalTile',
    'VerticalTileEdge' = 'VerticalTileEdge',
    'White' = 'White'
}
