/* autogenerated file using scripts/generateImEnums.ts */ 
export enum Weight {
    'Thin' = 'Thin',
    'ExtraLight' = 'ExtraLight',
    'UltraLight' = 'UltraLight',
    'Normal' = 'Normal',
    'Regular' = 'Regular',
    'Medium' = 'Medium',
    'DemiBold' = 'DemiBold',
    'SemiBold' = 'SemiBold',
    'Bold' = 'Bold',
    'ExtraBold' = 'ExtraBold',
    'UltraBold' = 'UltraBold',
    'Heavy' = 'Heavy',
    'Black' = 'Black'
}
