import { ConvertDemoImage } from './index';
import { CommandTemplate } from "../../components/argumentEditor/CommandTemplate";
import { toCliArg } from '../../../util/cli';
// import { toCliArg } from './index';

/** return a .sh script that will call imagemagick convert so we can generate te same transformations in the desktop with the real thing and compare */
export function getImCommands(images: ConvertDemoImage[], transformations: CommandTemplate[]): string {
  function getOutputFile(dir: any, image: ConvertDemoImage, transformation: CommandTemplate) {
    return `${dir}/${transformation.id}_${image.outFile}`
  }
  const dir = 'test1ImOutput'
  const cmd = `
# autogenerated script that apply test1 transformations and images on the desktop so we can compare to the real thing
npm run build
cd docs
rm -rf ${dir}
mkdir ${dir}
${images.map(image => {
      return transformations
        .map(t => {
          const command = t.command.map(arg => arg === '$INPUT' ? image.sourceUrl : arg === '$OUTPUT' ? getOutputFile(dir, image, t) : toCliArg(arg))
          return command.join(' ')
        }).join('\n')
    }).join('\n')}
`
  return cmd
}

// console.log(getImCommands(images, transformations))
