export enum Distort {
  Affine = 'Affine',
  AffineProjection = 'AffineProjection',
  ScaleRotateTranslate = 'ScaleRotateTranslate',
  SRT = 'SRT',
  Perspective = 'Perspective',
  PerspectiveProjection = 'PerspectiveProjection',
  BilinearForward = 'BilinearForward',
  BilinearReverse = 'BilinearReverse',
  Polynomial = 'Polynomial',
  Arc = 'Arc',
  Polar = 'Polar',
  DePolar = 'DePolar',
  Barrel = 'Barrel',
  BarrelInverse = 'BarrelInverse',
  Shepards = 'Shepards',
  Resize = 'Resize',
}